### ISSUE TITLE
The plan of code release

### ISSUE THREAD

**Issue by detectRecog** [minghanz/E2PN#1]
Hello, great work for 3D data analysing! What's the plan of code release, I'm quite interested in following your work.

**Comment by minghanz** [comment]
Hello, thanks for your interest! Please stay tuned. The code is close to ready and will be released soon.

**Comment by detectRecog** [comment]
@minghanz Hello, any news about the code release?

**Comment by DubiousCactus** [comment]
Hi @minghanz, any news on the code release?

**Comment by minghanz** [comment]
The code is now released. Thank you for your patience!
